"""Prepare an ESXi installer ISO for unattended (kickstart) install (ADR-0022).

ESXi's weasel installer activates kickstart mode when the kernel command line
carries ``ks=<source>``. We use ``ks=cdrom:/ks.cfg`` (single-CDROM mode): weasel
walks every attached CD-ROM for ``/ks.cfg``, and we inject it into the booted
installer ISO itself. Two-pass xorriso:

1. Extract ``/BOOT.CFG`` (BIOS, every ESXi 5+) and ``/EFI/BOOT/BOOT.CFG`` (UEFI,
   ESXi 7+ only — tolerate absence) and patch each ``kernelopt=`` line to
   ``runweasel ks=cdrom:/ks.cfg`` (DROP the original ``cdromBoot`` — it makes
   weasel handle the boot CD specially and skip the ks= search).
2. Re-emit the ISO with the patched configs back at their paths + ``ks.cfg`` at
   the root.

Load-bearing xorriso flags (from the proven ``esxi-kickstart.sh`` flow):

- ``-rockridge off`` — ESXi's stripped cdfs is pure ISO9660 and REJECTS
  Rock-Ridge-decorated entries; with RR on, ``ks.cfg`` is invisible to weasel.
- ``-compliance lowercase`` — strict ISO9660 uppercases filenames, so without
  this xorriso writes ``KS.CFG`` and weasel's case-sensitive ``ks=cdrom:/ks.cfg``
  lookup ENOENTs. Relaxing compliance keeps the lowercase entry (``BOOT.CFG``
  is authored uppercase on the source and stays that way).
- ``-boot_image any patch`` (NOT ``keep``) — updates ISOLINUX's boot-info-table
  self-LBA checksum after the injected files shift the layout; ``keep`` leaves a
  stale checksum and SeaBIOS bombs with "ISOLINUX: Image checksum error" before
  the kernel loads.
- ``-return_with FAILURE 32`` — same benign post-write MBR-size SORRY workaround
  as the PVE prep.

``ks.cfg`` is lowercase at the root: cdfs is case-sensitive, so
``ks=cdrom:/KS.CFG`` returns ENOENT against a lowercase entry.

This is a sanctioned ``subprocess`` use — see ADR-0022 (shared with the PVE prep
module); the project-wide ban (ADR-0001) carves out exactly these two modules.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import tempfile
from pathlib import Path

from testrange._log import get_logger
from testrange.exceptions import BuilderError

_log = get_logger(__name__)

# xorriso is run under a fixed C locale so the diagnostic strings _extract()
# matches on ("not found", "no such file", ...) stay stable regardless of the
# host's $LANG/$LC_MESSAGES.
_C_LOCALE_ENV = {**os.environ, "LC_ALL": "C"}

_BOOTCFG_BIOS = "/BOOT.CFG"
_BOOTCFG_UEFI = "/EFI/BOOT/BOOT.CFG"
_KICKSTART_KERNELOPT = "runweasel ks=cdrom:/ks.cfg"
_KICKSTART_FILENAME = "ks.cfg"
_SERIAL_DEVICE = "/dev/ttyS0"


class EsxiPrepareError(BuilderError):
    """Raised when preparing an ESXi installer ISO fails (missing ``xorriso``,
    a corrupt/unrecognized vanilla ISO, or a non-zero ``xorriso`` exit)."""


def render_kickstart(*, root_password: str, ssh_key: str | None = None) -> str:
    """Build a ks.cfg that installs ESXi unattended and reports a build result.

    The ``%firstboot`` block (busybox) optionally enables SSH + writes the key,
    then frames the build-result record to the serial console (ADR-0012) and
    powers off — replacing the prior power-off-edge keying. Provisioning runs in
    a ``set -e`` subshell so a failure emits ``fail`` (not a false ``ok``) and
    the guest still powers off.

    Args:
      root_password: plaintext root password (``rootpw``). ESXi enforces
        complexity (>=8 chars, mixed classes); the caller's Credential is the
        source of truth, so we only reject an empty password here.
      ssh_key: optional OpenSSH public key. When set, ``%firstboot`` enables
        sshd, opens the ``sshServer`` firewall ruleset, and writes the key to
        ``/etc/ssh/keys-root/authorized_keys`` (ESXi's path, NOT ``~root/.ssh``).
    """
    if not root_password:
        raise EsxiPrepareError(
            "ESXi kickstart requires a non-empty root_password "
            "(ESXi has no installable system without one)."
        )
    install = [
        "# Generated by ESXiKickstartBuilder — do not edit by hand.",
        "accepteula",
        f"rootpw {root_password}",
        # --firstdisk picks the first non-install-source disk; --overwritevmfs
        # clears any prior VMFS so a re-run is idempotent.
        "install --firstdisk --overwritevmfs",
        "network --bootproto=dhcp --device=vmnic0",
        "reboot",
        "",
        "%firstboot --interpreter=busybox",
    ]
    provision: list[str] = []
    if ssh_key:
        provision = [
            "vim-cmd hostsvc/enable_ssh",
            "vim-cmd hostsvc/start_ssh",
            "esxcli network firewall ruleset set --enabled=true --ruleset-id=sshServer",
            "mkdir -p /etc/ssh/keys-root",
            "cat > /etc/ssh/keys-root/authorized_keys <<'KEYEOF'",
            ssh_key,
            "KEYEOF",
            "chmod 600 /etc/ssh/keys-root/authorized_keys",
            "chown root:root /etc/ssh/keys-root/authorized_keys",
        ]
    # Always-powers-off, emits ok/fail. The subshell aborts on the first failure
    # under set -e; the `if` captures it so a half-provisioned install reports
    # `fail` instead of a false `ok`. --delay=10 lets %firstboot output flush.
    result = [
        "if (",
        "  set -e",
        *[f"  {line}" for line in provision],
        "  true",
        "); then",
        f'  echo "TESTRANGE-RESULT: ok" > {_SERIAL_DEVICE}',
        "else",
        f'  echo "TESTRANGE-RESULT: fail rc=$?" > {_SERIAL_DEVICE}',
        "fi",
        'esxcli system shutdown poweroff --reason="testrange install done" --delay=10',
    ]
    return "\n".join([*install, *result]) + "\n"


def prepare_iso(vanilla_iso: Path, out_path: Path, *, kickstart: str) -> None:
    """Write a kickstart-patched copy of *vanilla_iso* to *out_path* (two-pass).

    Args:
      vanilla_iso: existing ESXi installer ISO on disk.
      out_path: where to write the prepared ISO (overwritten if present).
      kickstart: ks.cfg body (see :func:`render_kickstart`).

    Raises:
      EsxiPrepareError: ``xorriso`` missing, the vanilla ISO is not a recognized
        ESXi image (no ``/BOOT.CFG``), or ``xorriso`` returns non-zero.
    """
    vanilla_iso = vanilla_iso.expanduser().resolve()
    out_path = out_path.expanduser().resolve()
    xorriso = shutil.which("xorriso")
    if xorriso is None:
        raise EsxiPrepareError(
            "xorriso not found on $PATH — install it with `apt install xorriso` "
            "(Debian/Ubuntu), `dnf install xorriso` (Fedora/RHEL), or `brew install "
            "xorriso` (macOS). Required to inject /ks.cfg + patch the ESXi boot "
            "configs while preserving the hybrid boot setup (ADR-0022)."
        )
    _log.info("preparing ESXi ISO %s -> %s", vanilla_iso, out_path)
    with tempfile.TemporaryDirectory(prefix="testrange-esxi-prep-") as td:
        tmp = Path(td)
        ks_path = tmp / _KICKSTART_FILENAME
        ks_path.write_text(kickstart, encoding="utf-8")

        bios_cfg = tmp / "BOOT.CFG"
        if not _extract(xorriso, vanilla_iso, _BOOTCFG_BIOS, bios_cfg):
            raise EsxiPrepareError(
                f"vanilla ESXi ISO {vanilla_iso} has no {_BOOTCFG_BIOS} — "
                "not a recognizable ESXi installer image."
            )
        _patch_bootcfg(bios_cfg)

        uefi_cfg = tmp / "BOOT.EFI.CFG"
        have_efi = _extract(xorriso, vanilla_iso, _BOOTCFG_UEFI, uefi_cfg)
        if have_efi:
            _patch_bootcfg(uefi_cfg)
        else:
            _log.info(
                "%s absent in vanilla ISO; assuming legacy-only (pre-7 ESXi) — "
                "UEFI boot will not work on the prepared ISO.",
                _BOOTCFG_UEFI,
            )

        cmd = [
            xorriso,
            "-return_with",
            "FAILURE",
            "32",
            # Keep ks.cfg LOWERCASE on the ISO: ESXi's cdfs is case-sensitive and
            # weasel looks up the exact ``ks=cdrom:/ks.cfg``, but strict ISO9660
            # uppercases names (xorriso would write ``KS.CFG`` and weasel'd ENOENT).
            # Relaxing compliance preserves the lowercase entry; ``BOOT.CFG`` stays
            # uppercase because that is how it is authored on the source.
            "-compliance",
            "lowercase",
            "-indev",
            str(vanilla_iso),
            "-rockridge",
            "off",
            "-outdev",
            str(out_path),
            "-boot_image",
            "any",
            "patch",
            "-map",
            str(ks_path),
            "/ks.cfg",
            "-map",
            str(bios_cfg),
            _BOOTCFG_BIOS,
        ]
        if have_efi:
            cmd.extend(["-map", str(uefi_cfg), _BOOTCFG_UEFI])
        cmd.append("-commit")
        _run_xorriso(cmd)


def _run_xorriso(argv: list[str]) -> None:
    try:
        subprocess.run(argv, check=True, capture_output=True, text=True, env=_C_LOCALE_ENV)
    except subprocess.CalledProcessError as exc:
        stderr = (exc.stderr or "").strip()
        raise EsxiPrepareError(
            f"xorriso failed (exit {exc.returncode}): {stderr or '(no stderr)'}"
        ) from exc
    except FileNotFoundError as exc:  # pragma: no cover — racy with which()
        raise EsxiPrepareError(f"xorriso disappeared between which() and exec(): {exc}") from exc


def _extract(xorriso: str, iso: Path, iso_path: str, out: Path) -> bool:
    """Extract *iso_path* from *iso* to *out*; return whether the file existed.

    A missing file is not an error (pre-7 ESXi ISOs lack the UEFI variant);
    anything else raises.
    """
    proc = subprocess.run(
        [xorriso, "-osirrox", "on", "-indev", str(iso), "-extract", iso_path, str(out)],
        capture_output=True,
        text=True,
        check=False,
        env=_C_LOCALE_ENV,
    )
    if proc.returncode != 0 and not out.exists():
        # A genuinely-absent source (the UEFI BOOT.CFG on a legacy-only ISO) is
        # not an error. xorriso words this several ways depending on version:
        # "not found", "No such file or directory", "Cannot determine attributes
        # of (ISO) source file". Match all so absence is tolerated; anything else
        # is a real failure.
        stderr = (proc.stderr or "").lower()
        if any(s in stderr for s in ("not found", "no such file", "cannot determine attributes")):
            return False
        raise EsxiPrepareError(
            f"xorriso -extract {iso_path!r} failed (exit {proc.returncode}): "
            f"{(proc.stderr or '').strip() or '(no stderr)'}"
        )
    if out.exists():
        # osirrox preserves the ISO's (often read-only) mode on the extracted
        # copy; make our temp file writable so _patch_bootcfg can rewrite it.
        out.chmod(0o644)
    return out.exists()


def _patch_bootcfg(path: Path) -> None:
    """Rewrite *path*'s ``kernelopt=`` line so weasel runs unattended.

    Idempotent (a config already carrying ``ks=cdrom:/ks.cfg`` is left alone); a
    config with no ``kernelopt=`` line gets one appended. Preserves the source's
    line endings (BOOT.CFGs are often CRLF on the wire) — read/write in BYTES, not
    ``read_text`` (whose universal-newline translation strips the ``\\r`` so the
    CRLF could never be detected).
    """
    raw = path.read_bytes()
    text = raw.decode("utf-8", errors="replace")
    if "ks=cdrom:/ks.cfg" in text:
        return
    new_lines: list[str] = []
    seen = False
    for line in text.splitlines():
        if line.startswith("kernelopt="):
            new_lines.append(f"kernelopt={_KICKSTART_KERNELOPT}")
            seen = True
        else:
            new_lines.append(line)
    if not seen:
        new_lines.append(f"kernelopt={_KICKSTART_KERNELOPT}")
    sep = "\r\n" if b"\r\n" in raw else "\n"
    path.write_bytes((sep.join(new_lines) + sep).encode("utf-8"))


__all__ = ["EsxiPrepareError", "prepare_iso", "render_kickstart"]
